if("undefined"==typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");!function(){var c=jQuery.fn.jquery.split(" ")[0].split(".");if(2>c[0]&&9>c[1]||1==c[0]&&9==c[1]&&1>c[2])throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher");}();
(function(c){c.fn.emulateTransitionEnd=function(h){var k=!1,e=this;return c(this).one("bsTransitionEnd",function(){k=!0}),setTimeout(function(){k||c(e).trigger(c.support.transition.end)},h),this};c(function(){c.support.transition=function(){var h,k=document.createElement("bootstrap"),e={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"};for(h in e)if(void 0!==k.style[h])return{end:e[h]};return!1}();c.support.transition&&
(c.event.special.bsTransitionEnd={bindType:c.support.transition.end,delegateType:c.support.transition.end,handle:function(h){return c(h.target).is(this)?h.handleObj.handler.apply(this,arguments):void 0}})})})(jQuery);
(function(c){function h(b){c(b).on("click",k,this.close)}var k='[data-dismiss="alert"]';h.VERSION="3.3.5";h.TRANSITION_DURATION=150;h.prototype.close=function(b){function a(){g.detach().trigger("closed.bs.alert").remove()}var d=c(this),f=d.attr("data-target");f||(f=(f=d.attr("href"))&&f.replace(/.*(?=#[^\s]*$)/,""));var g=c(f);b&&b.preventDefault();g.length||(g=d.closest(".alert"));g.trigger(b=c.Event("close.bs.alert"));b.isDefaultPrevented()||(g.removeClass("in"),c.support.transition&&g.hasClass("fade")?
g.one("bsTransitionEnd",a).emulateTransitionEnd(h.TRANSITION_DURATION):a())};var e=c.fn.alert;c.fn.alert=function(b){return this.each(function(){var a=c(this),d=a.data("bs.alert");d||a.data("bs.alert",d=new h(this));"string"==typeof b&&d[b].call(a)})};c.fn.alert.Constructor=h;c.fn.alert.noConflict=function(){return c.fn.alert=e,this};c(document).on("click.bs.alert.data-api",k,h.prototype.close)})(jQuery);
(function(c){function h(b){return this.each(function(){var a=c(this),d=a.data("bs.button");d||a.data("bs.button",d=new k(this,"object"==typeof b&&b));"toggle"==b?d.toggle():b&&d.setState(b)})}var k=function(b,a){this.$element=c(b);this.options=c.extend({},k.DEFAULTS,a);this.isLoading=!1};k.VERSION="3.3.5";k.DEFAULTS={loadingText:"loading..."};k.prototype.setState=function(b){var a=this.$element,d=a.is("input")?"val":"html",f=a.data();b+="Text";null==f.resetText&&a.data("resetText",a[d]());setTimeout(c.proxy(function(){a[d]((null==
f[b]?this.options:f)[b]);"loadingText"==b?(this.isLoading=!0,a.addClass("disabled").attr("disabled","disabled")):this.isLoading&&(this.isLoading=!1,a.removeClass("disabled").removeAttr("disabled"))},this),0)};k.prototype.toggle=function(){var b,a=!0,d=this.$element.closest('[data-toggle="buttons"]');d.length?("radio"==(b=this.$element.find("input")).prop("type")?(b.prop("checked")&&(a=!1),d.find(".active").removeClass("active"),this.$element.addClass("active")):"checkbox"==b.prop("type")&&(b.prop("checked")!==
this.$element.hasClass("active")&&(a=!1),this.$element.toggleClass("active")),b.prop("checked",this.$element.hasClass("active")),a&&b.trigger("change")):(this.$element.attr("aria-pressed",!this.$element.hasClass("active")),this.$element.toggleClass("active"))};var e=c.fn.button;c.fn.button=h;c.fn.button.Constructor=k;c.fn.button.noConflict=function(){return c.fn.button=e,this};c(document).on("click.bs.button.data-api",'[data-toggle^="button"]',function(b){var a=c(b.target);a.hasClass("btn")||(a=a.closest(".btn"));
h.call(a,"toggle");c(b.target).is('input[type="radio"]')||c(b.target).is('input[type="checkbox"]')||b.preventDefault()}).on("focus.bs.button.data-api blur.bs.button.data-api",'[data-toggle^="button"]',function(b){c(b.target).closest(".btn").toggleClass("focus",/^focus(in)?$/.test(b.type))})})(jQuery);
(function(c){function h(a){return this.each(function(){var d=c(this),f=d.data("bs.carousel"),g=c.extend({},k.DEFAULTS,d.data(),"object"==typeof a&&a),l="string"==typeof a?a:g.slide;f||d.data("bs.carousel",f=new k(this,g));"number"==typeof a?f.to(a):l?f[l]():g.interval&&f.pause().cycle()})}function k(a,d){this.$element=c(a);this.$indicators=this.$element.find(".carousel-indicators");this.options=d;this.$items=this.$active=this.interval=this.sliding=this.paused=null;this.options.keyboard&&this.$element.on("keydown.bs.carousel",
c.proxy(this.keydown,this));"hover"!=this.options.pause||"ontouchstart"in document.documentElement||this.$element.on("mouseenter.bs.carousel",c.proxy(this.pause,this)).on("mouseleave.bs.carousel",c.proxy(this.cycle,this))}function e(a){var d,f=c(this),g=c(f.attr("data-target")||(d=f.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""));g.hasClass("carousel")&&(d=c.extend({},g.data(),f.data()),(f=f.attr("data-slide-to"))&&(d.interval=!1),h.call(g,d),f&&g.data("bs.carousel").to(f),a.preventDefault())}k.VERSION=
"3.3.5";k.TRANSITION_DURATION=600;k.DEFAULTS={interval:5E3,pause:"hover",wrap:!0,keyboard:!0};k.prototype.keydown=function(a){if(!/input|textarea/i.test(a.target.tagName)){switch(a.which){case 37:this.prev();break;case 39:this.next();break;default:return}a.preventDefault()}};k.prototype.cycle=function(a){return a||(this.paused=!1),this.interval&&clearInterval(this.interval),this.options.interval&&!this.paused&&(this.interval=setInterval(c.proxy(this.next,this),this.options.interval)),this};k.prototype.getItemIndex=
function(a){return this.$items=a.parent().children(".item"),this.$items.index(a||this.$active)};k.prototype.getItemForDirection=function(a,d){var f=this.getItemIndex(d);return!("prev"==a&&0===f||"next"==a&&f==this.$items.length-1)||this.options.wrap?(a=(f+("prev"==a?-1:1))%this.$items.length,this.$items.eq(a)):d};k.prototype.to=function(a){var d=this,f=this.getItemIndex(this.$active=this.$element.find(".item.active"));return a>this.$items.length-1||0>a?void 0:this.sliding?this.$element.one("slid.bs.carousel",
function(){d.to(a)}):f==a?this.pause().cycle():this.slide(f<a?"next":"prev",this.$items.eq(a))};k.prototype.pause=function(a){return a||(this.paused=!0),this.$element.find(".next, .prev").length&&c.support.transition&&(this.$element.trigger(c.support.transition.end),this.cycle(!0)),this.interval=clearInterval(this.interval),this};k.prototype.next=function(){return this.sliding?void 0:this.slide("next")};k.prototype.prev=function(){return this.sliding?void 0:this.slide("prev")};k.prototype.slide=function(a,
d){var f=this.$element.find(".item.active"),g=d||this.getItemForDirection(a,f),l=this.interval,m="next"==a?"left":"right",n=this;if(g.hasClass("active"))return this.sliding=!1;var p=g[0];d=c.Event("slide.bs.carousel",{relatedTarget:p,direction:m});if(this.$element.trigger(d),!d.isDefaultPrevented()){this.sliding=!0;l&&this.pause();this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),(d=c(this.$indicators.children()[this.getItemIndex(g)]))&&d.addClass("active"));var q=c.Event("slid.bs.carousel",
{relatedTarget:p,direction:m});return c.support.transition&&this.$element.hasClass("slide")?(g.addClass(a),g[0].offsetWidth,f.addClass(m),g.addClass(m),f.one("bsTransitionEnd",function(){g.removeClass([a,m].join(" ")).addClass("active");f.removeClass(["active",m].join(" "));n.sliding=!1;setTimeout(function(){n.$element.trigger(q)},0)}).emulateTransitionEnd(k.TRANSITION_DURATION)):(f.removeClass("active"),g.addClass("active"),this.sliding=!1,this.$element.trigger(q)),l&&this.cycle(),this}};var b=c.fn.carousel;
c.fn.carousel=h;c.fn.carousel.Constructor=k;c.fn.carousel.noConflict=function(){return c.fn.carousel=b,this};c(document).on("click.bs.carousel.data-api","[data-slide]",e).on("click.bs.carousel.data-api","[data-slide-to]",e);c(window).on("load",function(){c('[data-ride="carousel"]').each(function(){var a=c(this);h.call(a,a.data())})})})(jQuery);
(function(c){function h(a){var d=a.attr("data-target")||(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");return c(d)}function k(a){return this.each(function(){var d=c(this),f=d.data("bs.collapse"),g=c.extend({},e.DEFAULTS,d.data(),"object"==typeof a&&a);!f&&g.toggle&&/show|hide/.test(a)&&(g.toggle=!1);f||d.data("bs.collapse",f=new e(this,g));"string"==typeof a&&f[a]()})}var e=function(a,d){this.$element=c(a);this.options=c.extend({},e.DEFAULTS,d);this.$trigger=c('[data-toggle="collapse"][href="#'+
a.id+'"],[data-toggle="collapse"][data-target="#'+a.id+'"]');this.transitioning=null;this.options.parent?this.$parent=this.getParent():this.addAriaAndCollapsedClass(this.$element,this.$trigger);this.options.toggle&&this.toggle()};e.VERSION="3.3.5";e.TRANSITION_DURATION=350;e.DEFAULTS={toggle:!0};e.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};e.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a=this.$parent&&this.$parent.children(".panel").children(".in, .collapsing");
if(!(a&&a.length&&(g=a.data("bs.collapse"))&&g.transitioning)){var d=c.Event("show.bs.collapse");if(this.$element.trigger(d),!d.isDefaultPrevented()){a&&a.length&&(k.call(a,"hide"),g||a.data("bs.collapse",null));var f=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[f](0).attr("aria-expanded",!0);this.$trigger.removeClass("collapsed").attr("aria-expanded",!0);this.transitioning=1;var g=function(){this.$element.removeClass("collapsing").addClass("collapse in")[f]("");this.transitioning=
0;this.$element.trigger("shown.bs.collapse")};if(!c.support.transition)return g.call(this);a=c.camelCase(["scroll",f].join("-"));this.$element.one("bsTransitionEnd",c.proxy(g,this)).emulateTransitionEnd(e.TRANSITION_DURATION)[f](this.$element[0][a])}}}};e.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=c.Event("hide.bs.collapse");if(this.$element.trigger(a),!a.isDefaultPrevented()){var d=this.dimension();return this.$element[d](this.$element[d]())[0].offsetHeight,
this.$element.addClass("collapsing").removeClass("collapse in").attr("aria-expanded",!1),this.$trigger.addClass("collapsed").attr("aria-expanded",!1),this.transitioning=1,a=function(){this.transitioning=0;this.$element.removeClass("collapsing").addClass("collapse").trigger("hidden.bs.collapse")},c.support.transition?void this.$element[d](0).one("bsTransitionEnd",c.proxy(a,this)).emulateTransitionEnd(e.TRANSITION_DURATION):a.call(this)}}};e.prototype.toggle=function(){this[this.$element.hasClass("in")?
"hide":"show"]()};e.prototype.getParent=function(){return c(this.options.parent).find('[data-toggle="collapse"][data-parent="'+this.options.parent+'"]').each(c.proxy(function(a,d){d=c(d);this.addAriaAndCollapsedClass(h(d),d)},this)).end()};e.prototype.addAriaAndCollapsedClass=function(a,d){var f=a.hasClass("in");a.attr("aria-expanded",f);d.toggleClass("collapsed",!f).attr("aria-expanded",f)};var b=c.fn.collapse;c.fn.collapse=k;c.fn.collapse.Constructor=e;c.fn.collapse.noConflict=function(){return c.fn.collapse=
b,this};c(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(a){var d=c(this);d.attr("data-target")||a.preventDefault();d=(a=h(d)).data("bs.collapse")?"toggle":d.data();k.call(a,d)})})(jQuery);
(function(c){function h(d){var f=d.attr("data-target");return f||(f=(f=d.attr("href"))&&/#[A-Za-z]/.test(f)&&f.replace(/.*(?=#[^\s]*$)/,"")),(f=f&&c(f))&&f.length?f:d.parent()}function k(d){d&&3===d.which||(c(".dropdown-backdrop").remove(),c(b).each(function(){var f=c(this),g=h(f),l={relatedTarget:this};g.hasClass("open")&&(d&&"click"==d.type&&/input|textarea/i.test(d.target.tagName)&&c.contains(g[0],d.target)||(g.trigger(d=c.Event("hide.bs.dropdown",l)),d.isDefaultPrevented()||(f.attr("aria-expanded",
"false"),g.removeClass("open").trigger("hidden.bs.dropdown",l))))}))}function e(d){c(d).on("click.bs.dropdown",this.toggle)}var b='[data-toggle="dropdown"]';e.VERSION="3.3.5";e.prototype.toggle=function(d){var f=c(this);if(!f.is(".disabled, :disabled")){var g=h(f),l=g.hasClass("open");if(k(),!l){if("ontouchstart"in document.documentElement&&!g.closest(".navbar-nav").length&&c(document.createElement("div")).addClass("dropdown-backdrop").insertAfter(c(this)).on("click",k),l={relatedTarget:this},g.trigger(d=
c.Event("show.bs.dropdown",l)),d.isDefaultPrevented())return;f.trigger("focus").attr("aria-expanded","true");g.toggleClass("open").trigger("shown.bs.dropdown",l)}return!1}};e.prototype.keydown=function(d){if(/(38|40|27|32)/.test(d.which)&&!/input|textarea/i.test(d.target.tagName)){var f=c(this);if(d.preventDefault(),d.stopPropagation(),!f.is(".disabled, :disabled")){var g=h(f),l=g.hasClass("open");if(!l&&27!=d.which||l&&27==d.which)return 27==d.which&&g.find(b).trigger("focus"),f.trigger("click");
(f=g.find(".dropdown-menu li:not(.disabled):visible a")).length&&(g=f.index(d.target),38==d.which&&0<g&&g--,40==d.which&&g<f.length-1&&g++,~g||(g=0),f.eq(g).trigger("focus"))}}};var a=c.fn.dropdown;c.fn.dropdown=function(d){return this.each(function(){var f=c(this),g=f.data("bs.dropdown");g||f.data("bs.dropdown",g=new e(this));"string"==typeof d&&g[d].call(f)})};c.fn.dropdown.Constructor=e;c.fn.dropdown.noConflict=function(){return c.fn.dropdown=a,this};c(document).on("click.bs.dropdown.data-api",
k).on("click.bs.dropdown.data-api",".dropdown form",function(d){d.stopPropagation()}).on("click.bs.dropdown.data-api",b,e.prototype.toggle).on("keydown.bs.dropdown.data-api",b,e.prototype.keydown).on("keydown.bs.dropdown.data-api",".dropdown-menu",e.prototype.keydown)})(jQuery);
(function(c){function h(b,a){return this.each(function(){var d=c(this),f=d.data("bs.modal"),g=c.extend({},k.DEFAULTS,d.data(),"object"==typeof b&&b);f||d.data("bs.modal",f=new k(this,g));"string"==typeof b?f[b](a):g.show&&f.show(a)})}function k(b,a){this.options=a;this.$body=c(document.body);this.$element=c(b);this.$dialog=this.$element.find(".modal-dialog");this.originalBodyPad=this.isShown=this.$backdrop=null;this.scrollbarWidth=0;this.ignoreBackdropClick=!1;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,
c.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))}k.VERSION="3.3.5";k.TRANSITION_DURATION=300;k.BACKDROP_TRANSITION_DURATION=150;k.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};k.prototype.toggle=function(b){return this.isShown?this.hide():this.show(b)};k.prototype.show=function(b){var a=this,d=c.Event("show.bs.modal",{relatedTarget:b});this.$element.trigger(d);this.isShown||d.isDefaultPrevented()||(this.isShown=!0,this.checkScrollbar(),this.setScrollbar(),this.$body.addClass("modal-open"),
this.escape(),this.resize(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',c.proxy(this.hide,this)),this.$dialog.on("mousedown.dismiss.bs.modal",function(){a.$element.one("mouseup.dismiss.bs.modal",function(f){c(f.target).is(a.$element)&&(a.ignoreBackdropClick=!0)})}),this.backdrop(function(){var f=c.support.transition&&a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(a.$body);a.$element.show().scrollTop(0);a.adjustDialog();f&&a.$element[0].offsetWidth;
a.$element.addClass("in");a.enforceFocus();var g=c.Event("shown.bs.modal",{relatedTarget:b});f?a.$dialog.one("bsTransitionEnd",function(){a.$element.trigger("focus").trigger(g)}).emulateTransitionEnd(k.TRANSITION_DURATION):a.$element.trigger("focus").trigger(g)}))};k.prototype.hide=function(b){b&&b.preventDefault();b=c.Event("hide.bs.modal");this.$element.trigger(b);this.isShown&&!b.isDefaultPrevented()&&(this.isShown=!1,this.escape(),this.resize(),c(document).off("focusin.bs.modal"),this.$element.removeClass("in").off("click.dismiss.bs.modal").off("mouseup.dismiss.bs.modal"),
this.$dialog.off("mousedown.dismiss.bs.modal"),c.support.transition&&this.$element.hasClass("fade")?this.$element.one("bsTransitionEnd",c.proxy(this.hideModal,this)).emulateTransitionEnd(k.TRANSITION_DURATION):this.hideModal())};k.prototype.enforceFocus=function(){c(document).off("focusin.bs.modal").on("focusin.bs.modal",c.proxy(function(b){this.$element[0]===b.target||this.$element.has(b.target).length||this.$element.trigger("focus")},this))};k.prototype.escape=function(){this.isShown&&this.options.keyboard?
this.$element.on("keydown.dismiss.bs.modal",c.proxy(function(b){27==b.which&&this.hide()},this)):this.isShown||this.$element.off("keydown.dismiss.bs.modal")};k.prototype.resize=function(){this.isShown?c(window).on("resize.bs.modal",c.proxy(this.handleUpdate,this)):c(window).off("resize.bs.modal")};k.prototype.hideModal=function(){var b=this;this.$element.hide();this.backdrop(function(){b.$body.removeClass("modal-open");b.resetAdjustments();b.resetScrollbar();b.$element.trigger("hidden.bs.modal")})};
k.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};k.prototype.backdrop=function(b){var a,d=this,f=this.$element.hasClass("fade")?"fade":"";this.isShown&&this.options.backdrop?(a=c.support.transition&&f,this.$backdrop=c(document.createElement("div")).addClass("modal-backdrop "+f).appendTo(this.$body),this.$element.on("click.dismiss.bs.modal",c.proxy(function(g){return this.ignoreBackdropClick?void(this.ignoreBackdropClick=!1):void(g.target===g.currentTarget&&
("static"==this.options.backdrop?this.$element[0].focus():this.hide()))},this)),a&&this.$backdrop[0].offsetWidth,this.$backdrop.addClass("in"),b&&(a?this.$backdrop.one("bsTransitionEnd",b).emulateTransitionEnd(k.BACKDROP_TRANSITION_DURATION):b())):!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),a=function(){d.removeBackdrop();b&&b()},c.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one("bsTransitionEnd",a).emulateTransitionEnd(k.BACKDROP_TRANSITION_DURATION):a()):
b&&b()};k.prototype.handleUpdate=function(){this.adjustDialog()};k.prototype.adjustDialog=function(){var b=this.$element[0].scrollHeight>document.documentElement.clientHeight;this.$element.css({paddingLeft:!this.bodyIsOverflowing&&b?this.scrollbarWidth:"",paddingRight:this.bodyIsOverflowing&&!b?this.scrollbarWidth:""})};k.prototype.resetAdjustments=function(){this.$element.css({paddingLeft:"",paddingRight:""})};k.prototype.checkScrollbar=function(){var b,a=window.innerWidth;a||(a=(b=document.documentElement.getBoundingClientRect()).right-
Math.abs(b.left));this.bodyIsOverflowing=document.body.clientWidth<a;this.scrollbarWidth=this.measureScrollbar()};k.prototype.setScrollbar=function(){var b=parseInt(this.$body.css("padding-right")||0,10);this.originalBodyPad=document.body.style.paddingRight||"";this.bodyIsOverflowing&&this.$body.css("padding-right",b+this.scrollbarWidth)};k.prototype.resetScrollbar=function(){this.$body.css("padding-right",this.originalBodyPad)};k.prototype.measureScrollbar=function(){var b=document.createElement("div");
b.className="modal-scrollbar-measure";this.$body.append(b);var a=b.offsetWidth-b.clientWidth;return this.$body[0].removeChild(b),a};var e=c.fn.modal;c.fn.modal=h;c.fn.modal.Constructor=k;c.fn.modal.noConflict=function(){return c.fn.modal=e,this};c(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(b){var a=c(this),d=a.attr("href"),f=c(a.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""));d=f.data("bs.modal")?"toggle":c.extend({remote:!/#/.test(d)&&d},f.data(),a.data());a.is("a")&&
b.preventDefault();f.one("show.bs.modal",function(g){g.isDefaultPrevented()||f.one("hidden.bs.modal",function(){a.is(":visible")&&a.trigger("focus")})});h.call(f,d,this)})})(jQuery);
(function(c){function h(e,b){this.inState=this.$element=this.hoverState=this.timeout=this.enabled=this.options=this.type=null;this.init("tooltip",e,b)}h.VERSION="3.3.5";h.TRANSITION_DURATION=150;h.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1,viewport:{selector:"body",padding:0}};h.prototype.init=function(e,b,a){if(this.enabled=
!0,this.type=e,this.$element=c(b),this.options=this.getOptions(a),this.$viewport=this.options.viewport&&c(c.isFunction(this.options.viewport)?this.options.viewport.call(this,this.$element):this.options.viewport.selector||this.options.viewport),this.inState={click:!1,hover:!1,focus:!1},this.$element[0]instanceof document.constructor&&!this.options.selector)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");e=this.options.trigger.split(" ");
for(b=e.length;b--;){var d;a=e[b];"click"==a?this.$element.on("click."+this.type,this.options.selector,c.proxy(this.toggle,this)):"manual"!=a&&(d="hover"==a?"mouseenter":"focusin",a="hover"==a?"mouseleave":"focusout",this.$element.on(d+"."+this.type,this.options.selector,c.proxy(this.enter,this)),this.$element.on(a+"."+this.type,this.options.selector,c.proxy(this.leave,this)))}this.options.selector?this._options=c.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};h.prototype.getDefaults=
function(){return h.DEFAULTS};h.prototype.getOptions=function(e){return(e=c.extend({},this.getDefaults(),this.$element.data(),e)).delay&&"number"==typeof e.delay&&(e.delay={show:e.delay,hide:e.delay}),e};h.prototype.getDelegateOptions=function(){var e={},b=this.getDefaults();return this._options&&c.each(this._options,function(a,d){b[a]!=d&&(e[a]=d)}),e};h.prototype.enter=function(e){var b=e instanceof this.constructor?e:c(e.currentTarget).data("bs."+this.type);return b||(b=new this.constructor(e.currentTarget,
this.getDelegateOptions()),c(e.currentTarget).data("bs."+this.type,b)),e instanceof c.Event&&(b.inState["focusin"==e.type?"focus":"hover"]=!0),b.tip().hasClass("in")||"in"==b.hoverState?void(b.hoverState="in"):(clearTimeout(b.timeout),b.hoverState="in",b.options.delay&&b.options.delay.show?void(b.timeout=setTimeout(function(){"in"==b.hoverState&&b.show()},b.options.delay.show)):b.show())};h.prototype.isInStateTrue=function(){for(var e in this.inState)if(this.inState[e])return!0;return!1};h.prototype.leave=
function(e){var b=e instanceof this.constructor?e:c(e.currentTarget).data("bs."+this.type);return b||(b=new this.constructor(e.currentTarget,this.getDelegateOptions()),c(e.currentTarget).data("bs."+this.type,b)),e instanceof c.Event&&(b.inState["focusout"==e.type?"focus":"hover"]=!1),b.isInStateTrue()?void 0:(clearTimeout(b.timeout),b.hoverState="out",b.options.delay&&b.options.delay.hide?void(b.timeout=setTimeout(function(){"out"==b.hoverState&&b.hide()},b.options.delay.hide)):b.hide())};h.prototype.show=
function(){var e,b,a,d,f,g,l,m=c.Event("show.bs."+this.type);this.hasContent()&&this.enabled&&(this.$element.trigger(m),a=c.contains(this.$element[0].ownerDocument.documentElement,this.$element[0]),!m.isDefaultPrevented()&&a&&(b=(e=this).tip(),g=this.getUID(this.type),this.setContent(),b.attr("id",g),this.$element.attr("aria-describedby",g),this.options.animation&&b.addClass("fade"),l="function"==typeof this.options.placement?this.options.placement.call(this,b[0],this.$element[0]):this.options.placement,
(f=(d=/\s?auto?\s?/i).test(l))&&(l=l.replace(d,"")||"top"),b.detach().css({top:0,left:0,display:"block"}).addClass(l).data("bs."+this.type,this),this.options.container?b.appendTo(this.options.container):b.insertAfter(this.$element),this.$element.trigger("inserted.bs."+this.type),m=this.getPosition(),a=b[0].offsetWidth,g=b[0].offsetHeight,f&&(d=l,f=this.getPosition(this.$viewport),l="bottom"==l&&m.bottom+g>f.bottom?"top":"top"==l&&m.top-g<f.top?"bottom":"right"==l&&m.right+a>f.width?"left":"left"==
l&&m.left-a<f.left?"right":l,b.removeClass(d).addClass(l)),g=this.getCalculatedOffset(l,m,a,g),this.applyPlacement(g,l),l=function(){var n=e.hoverState;e.$element.trigger("shown.bs."+e.type);e.hoverState=null;"out"==n&&e.leave(e)},c.support.transition&&this.$tip.hasClass("fade")?b.one("bsTransitionEnd",l).emulateTransitionEnd(h.TRANSITION_DURATION):l()))};h.prototype.applyPlacement=function(e,b){var a=this.tip(),d=a[0].offsetWidth,f=a[0].offsetHeight,g=parseInt(a.css("margin-top"),10),l=parseInt(a.css("margin-left"),
10);isNaN(g)&&(g=0);isNaN(l)&&(l=0);e.top+=g;e.left+=l;c.offset.setOffset(a[0],c.extend({using:function(n){a.css({top:Math.round(n.top),left:Math.round(n.left)})}},e),0);a.addClass("in");var m=a[0].offsetWidth;g=a[0].offsetHeight;"top"==b&&g!=f&&(e.top=e.top+f-g);(l=this.getViewportAdjustedDelta(b,e,m,g)).left?e.left+=l.left:e.top+=l.top;f=(b=/top|bottom/.test(b))?2*l.left-d+m:2*l.top-f+g;g=b?"offsetWidth":"offsetHeight";a.offset(e);this.replaceArrow(f,a[0][g],b)};h.prototype.replaceArrow=function(e,
b,a){this.arrow().css(a?"left":"top",50*(1-e/b)+"%").css(a?"top":"left","")};h.prototype.setContent=function(){var e=this.tip(),b=this.getTitle();e.find(".tooltip-inner")[this.options.html?"html":"text"](b);e.removeClass("fade in top bottom left right")};h.prototype.hide=function(e){function b(){"in"!=a.hoverState&&d.detach();a.$element.removeAttr("aria-describedby").trigger("hidden.bs."+a.type);e&&e()}var a=this,d=c(this.$tip),f=c.Event("hide.bs."+this.type);return this.$element.trigger(f),f.isDefaultPrevented()?
void 0:(d.removeClass("in"),c.support.transition&&d.hasClass("fade")?d.one("bsTransitionEnd",b).emulateTransitionEnd(h.TRANSITION_DURATION):b(),this.hoverState=null,this)};h.prototype.fixTitle=function(){var e=this.$element;(e.attr("title")||"string"!=typeof e.attr("data-original-title"))&&e.attr("data-original-title",e.attr("title")||"").attr("title","")};h.prototype.hasContent=function(){return this.getTitle()};h.prototype.getPosition=function(e){var b=(e=e||this.$element)[0],a="BODY"==b.tagName,
d=b.getBoundingClientRect();return null==d.width&&(d=c.extend({},d,{width:d.right-d.left,height:d.bottom-d.top})),b=a?{top:0,left:0}:e.offset(),e={scroll:a?document.documentElement.scrollTop||document.body.scrollTop:e.scrollTop()},a=a?{width:c(window).width(),height:c(window).height()}:null,c.extend({},d,e,a,b)};h.prototype.getCalculatedOffset=function(e,b,a,d){return"bottom"==e?{top:b.top+b.height,left:b.left+b.width/2-a/2}:"top"==e?{top:b.top-d,left:b.left+b.width/2-a/2}:"left"==e?{top:b.top+b.height/
2-d/2,left:b.left-a}:{top:b.top+b.height/2-d/2,left:b.left+b.width}};h.prototype.getViewportAdjustedDelta=function(e,b,a,d){var f={top:0,left:0};if(!this.$viewport)return f;var g,l=this.options.viewport&&this.options.viewport.padding||0,m=this.getPosition(this.$viewport);return/right|left/.test(e)?(e=b.top-l-m.scroll,g=b.top+l-m.scroll+d,e<m.top?f.top=m.top-e:g>m.top+m.height&&(f.top=m.top+m.height-g)):(g=b.left-l,a=b.left+l+a,g<m.left?f.left=m.left-g:a>m.right&&(f.left=m.left+m.width-a)),f};h.prototype.getTitle=
function(){var e=this.$element,b=this.options;return e.attr("data-original-title")||("function"==typeof b.title?b.title.call(e[0]):b.title)};h.prototype.getUID=function(e){for(;e+=~~(1E6*Math.random()),document.getElementById(e););return e};h.prototype.tip=function(){if(!this.$tip&&(this.$tip=c(this.options.template),1!=this.$tip.length))throw Error(this.type+" `template` option must consist of exactly 1 top-level element!");return this.$tip};h.prototype.arrow=function(){return this.$arrow=this.$arrow||
this.tip().find(".tooltip-arrow")};h.prototype.enable=function(){this.enabled=!0};h.prototype.disable=function(){this.enabled=!1};h.prototype.toggleEnabled=function(){this.enabled=!this.enabled};h.prototype.toggle=function(e){var b=this;e&&((b=c(e.currentTarget).data("bs."+this.type))||(b=new this.constructor(e.currentTarget,this.getDelegateOptions()),c(e.currentTarget).data("bs."+this.type,b)));e?(b.inState.click=!b.inState.click,b.isInStateTrue()?b.enter(b):b.leave(b)):b.tip().hasClass("in")?b.leave(b):
b.enter(b)};h.prototype.destroy=function(){var e=this;clearTimeout(this.timeout);this.hide(function(){e.$element.off("."+e.type).removeData("bs."+e.type);e.$tip&&e.$tip.detach();e.$tip=null;e.$arrow=null;e.$viewport=null})};var k=c.fn.tooltip;c.fn.tooltip=function(e){return this.each(function(){var b=c(this),a=b.data("bs.tooltip");!a&&/destroy|hide/.test(e)||(a||b.data("bs.tooltip",a=new h(this,"object"==typeof e&&e)),"string"==typeof e&&a[e]())})};c.fn.tooltip.Constructor=h;c.fn.tooltip.noConflict=
function(){return c.fn.tooltip=k,this}})(jQuery);
(function(c){function h(e,b){this.init("popover",e,b)}if(!c.fn.tooltip)throw Error("Popover requires tooltip.js");h.VERSION="3.3.5";h.DEFAULTS=c.extend({},c.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});((h.prototype=c.extend({},c.fn.tooltip.Constructor.prototype)).constructor=h).prototype.getDefaults=function(){return h.DEFAULTS};
h.prototype.setContent=function(){var e=this.tip(),b=this.getTitle(),a=this.getContent();e.find(".popover-title")[this.options.html?"html":"text"](b);e.find(".popover-content").children().detach().end()[this.options.html?"string"==typeof a?"html":"append":"text"](a);e.removeClass("fade top bottom left right in");e.find(".popover-title").html()||e.find(".popover-title").hide()};h.prototype.hasContent=function(){return this.getTitle()||this.getContent()};h.prototype.getContent=function(){var e=this.$element,
b=this.options;return e.attr("data-content")||("function"==typeof b.content?b.content.call(e[0]):b.content)};h.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};var k=c.fn.popover;c.fn.popover=function(e){return this.each(function(){var b=c(this),a=b.data("bs.popover");!a&&/destroy|hide/.test(e)||(a||b.data("bs.popover",a=new h(this,"object"==typeof e&&e)),"string"==typeof e&&a[e]())})};c.fn.popover.Constructor=h;c.fn.popover.noConflict=function(){return c.fn.popover=
k,this}})(jQuery);
(function(c){function h(b,a){this.$body=c(document.body);this.$scrollElement=c(c(b).is(document.body)?window:b);this.options=c.extend({},h.DEFAULTS,a);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",c.proxy(this.process,this));this.refresh();this.process()}function k(b){return this.each(function(){var a=c(this),d=a.data("bs.scrollspy");d||a.data("bs.scrollspy",d=new h(this,
"object"==typeof b&&b));"string"==typeof b&&d[b]()})}h.VERSION="3.3.5";h.DEFAULTS={offset:10};h.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};h.prototype.refresh=function(){var b=this,a="offset",d=0;this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();c.isWindow(this.$scrollElement[0])||(a="position",d=this.$scrollElement.scrollTop());this.$body.find(this.selector).map(function(){var f=
c(this),g=f.data("target")||f.attr("href");return(f=/^#./.test(g)&&c(g))&&f.length&&f.is(":visible")?[[f[a]().top+d,g]]:null}).sort(function(f,g){return f[0]-g[0]}).each(function(){b.offsets.push(this[0]);b.targets.push(this[1])})};h.prototype.process=function(){var b,a=this.$scrollElement.scrollTop()+this.options.offset,d=this.getScrollHeight(),f=this.options.offset+d-this.$scrollElement.height(),g=this.offsets,l=this.targets,m=this.activeTarget;if(this.scrollHeight!=d&&this.refresh(),f<=a)return m!=
(b=l[l.length-1])&&this.activate(b);if(m&&a<g[0])return this.activeTarget=null,this.clear();for(b=g.length;b--;)m!=l[b]&&a>=g[b]&&(void 0===g[b+1]||a<g[b+1])&&this.activate(l[b])};h.prototype.activate=function(b){this.activeTarget=b;this.clear();(b=c(b=this.selector+'[data-target="'+b+'"],'+this.selector+'[href="'+b+'"]').parents("li").addClass("active")).parent(".dropdown-menu").length&&(b=b.closest("li.dropdown").addClass("active"));b.trigger("activate.bs.scrollspy")};h.prototype.clear=function(){c(this.selector).parentsUntil(this.options.target,
".active").removeClass("active")};var e=c.fn.scrollspy;c.fn.scrollspy=k;c.fn.scrollspy.Constructor=h;c.fn.scrollspy.noConflict=function(){return c.fn.scrollspy=e,this};c(window).on("load.bs.scrollspy.data-api",function(){c('[data-spy="scroll"]').each(function(){var b=c(this);k.call(b,b.data())})})})(jQuery);
(function(c){function h(a){return this.each(function(){var d=c(this),f=d.data("bs.tab");f||d.data("bs.tab",f=new k(this));"string"==typeof a&&f[a]()})}function k(a){this.element=c(a)}function e(a){a.preventDefault();h.call(c(this),"show")}k.VERSION="3.3.5";k.TRANSITION_DURATION=150;k.prototype.show=function(){var a,d,f,g=this.element,l=g.closest("ul:not(.dropdown-menu)"),m=g.data("target");m||(m=(m=g.attr("href"))&&m.replace(/.*(?=#[^\s]*$)/,""));g.parent("li").hasClass("active")||(a=l.find(".active:last a"),
d=c.Event("hide.bs.tab",{relatedTarget:g[0]}),f=c.Event("show.bs.tab",{relatedTarget:a[0]}),a.trigger(d),g.trigger(f),f.isDefaultPrevented()||d.isDefaultPrevented()||(m=c(m),this.activate(g.closest("li"),l),this.activate(m,m.parent(),function(){a.trigger({type:"hidden.bs.tab",relatedTarget:g[0]});g.trigger({type:"shown.bs.tab",relatedTarget:a[0]})})))};k.prototype.activate=function(a,d,f){function g(){l.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",
!1);a.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",!0);m?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu").length&&a.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0);f&&f()}var l=d.find("> .active"),m=f&&c.support.transition&&(l.length&&l.hasClass("fade")||!!d.find("> .fade").length);l.length&&m?l.one("bsTransitionEnd",g).emulateTransitionEnd(k.TRANSITION_DURATION):g();l.removeClass("in")};
var b=c.fn.tab;c.fn.tab=h;c.fn.tab.Constructor=k;c.fn.tab.noConflict=function(){return c.fn.tab=b,this};c(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',e).on("click.bs.tab.data-api",'[data-toggle="pill"]',e)})(jQuery);
(function(c){function h(b){return this.each(function(){var a=c(this),d=a.data("bs.affix");d||a.data("bs.affix",d=new k(this,"object"==typeof b&&b));"string"==typeof b&&d[b]()})}var k=function(b,a){this.options=c.extend({},k.DEFAULTS,a);this.$target=c(this.options.target).on("scroll.bs.affix.data-api",c.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",c.proxy(this.checkPositionWithEventLoop,this));this.$element=c(b);this.pinnedOffset=this.unpin=this.affixed=null;this.checkPosition()};k.VERSION=
"3.3.5";k.RESET="affix affix-top affix-bottom";k.DEFAULTS={offset:0,target:window};k.prototype.getState=function(b,a,d,f){var g=this.$target.scrollTop(),l=this.$element.offset(),m=this.$target.height();if(null!=d&&"top"==this.affixed)return g<d&&"top";if("bottom"==this.affixed)return null!=d?!(g+this.unpin<=l.top)&&"bottom":!(g+m<=b-f)&&"bottom";var n=null==this.affixed;l=n?g:l.top;return null!=d&&g<=d?"top":null!=f&&b-f<=l+(n?m:a)&&"bottom"};k.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;
this.$element.removeClass(k.RESET).addClass("affix");var b=this.$target.scrollTop();return this.pinnedOffset=this.$element.offset().top-b};k.prototype.checkPositionWithEventLoop=function(){setTimeout(c.proxy(this.checkPosition,this),1)};k.prototype.checkPosition=function(){if(this.$element.is(":visible")){var b=this.$element.height(),a=this.options.offset,d=a.top,f=a.bottom,g=Math.max(c(document).height(),c(document.body).height());"object"!=typeof a&&(f=d=a);"function"==typeof d&&(d=a.top(this.$element));
"function"==typeof f&&(f=a.bottom(this.$element));var l=this.getState(g,b,d,f);if(this.affixed!=l){if(null!=this.unpin&&this.$element.css("top",""),a="affix"+(l?"-"+l:""),d=c.Event(a+".bs.affix"),this.$element.trigger(d),d.isDefaultPrevented())return;this.affixed=l;this.unpin="bottom"==l?this.getPinnedOffset():null;this.$element.removeClass(k.RESET).addClass(a).trigger(a.replace("affix","affixed")+".bs.affix")}"bottom"==l&&this.$element.offset({top:g-b-f})}};var e=c.fn.affix;c.fn.affix=h;c.fn.affix.Constructor=
k;c.fn.affix.noConflict=function(){return c.fn.affix=e,this};c(window).on("load",function(){c('[data-spy="affix"]').each(function(){var b=c(this),a=b.data();a.offset=a.offset||{};null!=a.offsetBottom&&(a.offset.bottom=a.offsetBottom);null!=a.offsetTop&&(a.offset.top=a.offsetTop);h.call(b,a)})})})(jQuery);