!function(d){var B=[],y={options:{prependExistingHelpBlock:!1,sniffHtml:!0,preventSubmit:!0,submitError:!1,submitSuccess:!1,semanticallyStrict:!1,autoAdd:{helpBlocks:!0},filter:function(){return!0}},methods:{init:function(c){var b=d.extend(!0,{},y);b.options=d.extend(!0,b.options,c);c=d.unique(this.map(function(){return d(this).parents("form")[0]}).toArray());return d(c).bind("submit",function(a){var f=d(this),g=0,q=f.find("input,textarea,select").not("[type=submit],[type=image]").filter(b.options.filter);
q.trigger("submit.validation").trigger("validationLostFocus.validation");q.each(function(n,e){var p=d(e).parents(".form-group, .checkbox").first();p.hasClass("warning")&&(p.removeClass("warning").addClass("error"),g++)});q.trigger("validationLostFocus.validation");g?(b.options.preventSubmit&&a.preventDefault(),f.addClass("error"),d.isFunction(b.options.submitError)&&b.options.submitError(f,a,q.jqBootstrapValidation("collectErrors",!0))):(f.removeClass("error"),d.isFunction(b.options.submitSuccess)&&
b.options.submitSuccess(f,a))}),this.each(function(){var a=d(this),f=a.parents(".form-group, .checkbox").first(),g=f.find(".help-block").first(),q=a.parents("form").first(),n=[];if(!g.length&&b.options.autoAdd&&b.options.autoAdd.helpBlocks&&(g=d('<div class="help-block" />'),f.append(g),B.push(g[0])),b.options.sniffHtml){var e="";if(void 0!==a.attr("pattern")&&(e="Not in the expected format\x3c!-- data-validation-pattern-message to override --\x3e",a.data("validationPatternMessage")&&(e=a.data("validationPatternMessage")),
a.data("validationPatternMessage",e),a.data("validationPatternRegex",a.attr("pattern"))),void 0!==a.attr("max")||void 0!==a.attr("aria-valuemax")){var p=void 0!==a.attr("max")?a.attr("max"):a.attr("aria-valuemax");e="Too high: Maximum of '"+p+"'\x3c!-- data-validation-max-message to override --\x3e";a.data("validationMaxMessage")&&(e=a.data("validationMaxMessage"));a.data("validationMaxMessage",e);a.data("validationMaxMax",p)}if(void 0!==a.attr("min")||void 0!==a.attr("aria-valuemin"))p=void 0!==
a.attr("min")?a.attr("min"):a.attr("aria-valuemin"),e="Too low: Minimum of '"+p+"'\x3c!-- data-validation-min-message to override --\x3e",a.data("validationMinMessage")&&(e=a.data("validationMinMessage")),a.data("validationMinMessage",e),a.data("validationMinMin",p);void 0!==a.attr("maxlength")&&(e="Too long: Maximum of '"+a.attr("maxlength")+"' characters\x3c!-- data-validation-maxlength-message to override --\x3e",a.data("validationMaxlengthMessage")&&(e=a.data("validationMaxlengthMessage")),a.data("validationMaxlengthMessage",
e),a.data("validationMaxlengthMaxlength",a.attr("maxlength")));void 0!==a.attr("minlength")&&(e="Too short: Minimum of '"+a.attr("minlength")+"' characters\x3c!-- data-validation-minlength-message to override --\x3e",a.data("validationMinlengthMessage")&&(e=a.data("validationMinlengthMessage")),a.data("validationMinlengthMessage",e),a.data("validationMinlengthMinlength",a.attr("minlength")));void 0===a.attr("required")&&void 0===a.attr("aria-required")||(e=b.builtInValidators.required.message,a.data("validationRequiredMessage")&&
(e=a.data("validationRequiredMessage")),a.data("validationRequiredMessage",e));void 0!==a.attr("type")&&"number"===a.attr("type").toLowerCase()&&(e=b.builtInValidators.number.message,a.data("validationNumberMessage")&&(e=a.data("validationNumberMessage")),a.data("validationNumberMessage",e));void 0!==a.attr("type")&&"email"===a.attr("type").toLowerCase()&&(e="Not a valid email address\x3c!-- data-validator-validemail-message to override --\x3e",a.data("validationValidemailMessage")?e=a.data("validationValidemailMessage"):
a.data("validationEmailMessage")&&(e=a.data("validationEmailMessage")),a.data("validationValidemailMessage",e));void 0!==a.attr("minchecked")&&(e="Not enough options checked; Minimum of '"+a.attr("minchecked")+"' required\x3c!-- data-validation-minchecked-message to override --\x3e",a.data("validationMincheckedMessage")&&(e=a.data("validationMincheckedMessage")),a.data("validationMincheckedMessage",e),a.data("validationMincheckedMinchecked",a.attr("minchecked")));void 0!==a.attr("maxchecked")&&(e=
"Too many options checked; Maximum of '"+a.attr("maxchecked")+"' required\x3c!-- data-validation-maxchecked-message to override --\x3e",a.data("validationMaxcheckedMessage")&&(e=a.data("validationMaxcheckedMessage")),a.data("validationMaxcheckedMessage",e),a.data("validationMaxcheckedMaxchecked",a.attr("maxchecked")))}void 0!==a.data("validation")&&(n=a.data("validation").split(","));d.each(a.data(),function(w,h){var k=w.replace(/([A-Z])/g,",$1").split(",");"validation"===k[0]&&k[1]&&n.push(k[1])});
e=n;var A=[];do d.each(n,function(w,h){n[w]=z(h)}),n=d.unique(n),A=[],d.each(e,function(w,h){if(void 0!==a.data("validation"+h+"Shortcut"))d.each(a.data("validation"+h+"Shortcut").split(","),function(m,l){A.push(l)});else if(b.builtInValidators[h.toLowerCase()]){var k=b.builtInValidators[h.toLowerCase()];"shortcut"===k.type.toLowerCase()&&d.each(k.shortcut.split(","),function(m,l){l=z(l);A.push(l);n.push(l)})}}),e=A;while(0<e.length);var x={};d.each(n,function(w,h){var k=a.data("validation"+h+"Message"),
m=void 0!==k,l=!1;if(k=k||"'"+h+"' validation failed \x3c!-- Add attribute 'data-validation-"+h.toLowerCase()+"-message' to input to change this message --\x3e",d.each(b.validatorTypes,function(r,u){void 0===x[r]&&(x[r]=[]);l||void 0===a.data("validation"+h+z(u.name))||(x[r].push(d.extend(!0,{name:z(u.name),message:k},u.init(a,h))),l=!0)}),!l&&b.builtInValidators[h.toLowerCase()]){var t=d.extend(!0,{},b.builtInValidators[h.toLowerCase()]);m&&(t.message=k);var v=t.type.toLowerCase();"shortcut"===v?
l=!0:d.each(b.validatorTypes,function(r,u){void 0===x[r]&&(x[r]=[]);l||v!==r.toLowerCase()||(a.data("validation"+h+z(u.name),t[u.name.toLowerCase()]),x[v].push(d.extend(t,u.init(a,h))),l=!0)})}l||d.error("Cannot find validation info for '"+h+"'")});g.data("original-contents",g.data("original-contents")?g.data("original-contents"):g.html());g.data("original-role",g.data("original-role")?g.data("original-role"):g.attr("role"));f.data("original-classes",f.data("original-clases")?f.data("original-classes"):
f.attr("class"));a.data("original-aria-invalid",a.data("original-aria-invalid")?a.data("original-aria-invalid"):a.attr("aria-invalid"));a.bind("validation.validation",function(w,h){var k=C(a),m=[];return d.each(x,function(l,t){(k||k.length||h&&h.includeEmpty||b.validatorTypes[l].blockSubmit&&h&&h.submitting)&&d.each(t,function(v,r){b.validatorTypes[l].validate(a,k,r)&&m.push(r.message)})}),m});a.bind("getValidators.validation",function(){return x});a.bind("submit.validation",function(){return a.triggerHandler("change.validation",
{submitting:!0})});a.bind("keyup.validation focus.validation blur.validation click.validation keydown.validation keypress.validation change.validation",function(w,h){var k=C(a),m=[];f.find("input,textarea,select").each(function(l,t){var v=m.length;(d.each(d(t).triggerHandler("validation.validation",h),function(r,u){m.push(u)}),m.length>v)?d(t).attr("aria-invalid","true"):(v=a.data("original-aria-invalid"),d(t).attr("aria-invalid",void 0!==v&&v))});q.find("input,select,textarea").not(a).not('[name="'+
a.attr("name")+'"]').trigger("validationLostFocus.validation");(m=d.unique(m.sort())).length?(f.removeClass("success error").addClass("warning"),b.options.semanticallyStrict&&1===m.length?g.html(m[0]+(b.options.prependExistingHelpBlock?g.data("original-contents"):"")):g.html('<ul class="list-unstyled alert alert-warning" role="alert"><li>'+m.join("</li><li>")+"</li></ul>"+(b.options.prependExistingHelpBlock?g.data("original-contents"):""))):(f.removeClass("warning error success"),0<k.length&&f.addClass("success"),
g.html(g.data("original-contents")));"blur"===w.type&&f.removeClass("success")});a.bind("validationLostFocus.validation",function(){f.removeClass("success")})})},destroy:function(){return this.each(function(){var c=d(this),b=c.parents(".form-group, .checkbox").first(),a=b.find(".help-block").first();c.unbind(".validation");a.html(a.data("original-contents"));b.attr("class",b.data("original-classes"));c.attr("aria-invalid",c.data("original-aria-invalid"));a.attr("role",c.data("original-role"));-1<
B.indexOf(a[0])&&a.remove()})},collectErrors:function(c){var b={};return this.each(function(a,f){var g=d(f),q=g.attr("name");g=g.triggerHandler("validation.validation",{includeEmpty:!0});b[q]=d.extend(!0,g,b[q])}),d.each(b,function(a,f){0===f.length&&delete b[a]}),b},hasErrors:function(){var c=[];return this.each(function(b,a){c=c.concat(d(a).triggerHandler("getValidators.validation")?d(a).triggerHandler("validation.validation",{submitting:!0}):[])}),0<c.length},override:function(c){y=d.extend(!0,
y,c)}},validatorTypes:{callback:{name:"callback",init:function(c,b){return{validatorName:b,callback:c.data("validation"+b+"Callback"),lastValue:c.val(),lastValid:!0,lastFinished:!0}},validate:function(c,b,a){if(a.lastValue===b&&a.lastFinished)return!a.lastValid;!0===a.lastFinished&&(a.lastValue=b,a.lastValid=!0,a.lastFinished=!1,!function(f,g){for(var q=Array.prototype.slice.call(arguments).splice(2),n=f.split("."),e=n.pop(),p=0;p<n.length;p++)g=g[n[p]];return g[e].apply(this,q)}(a.callback,window,
c,b,function(f){a.lastValue===f.value&&(a.lastValid=f.valid,f.message&&(a.message=f.message),a.lastFinished=!0,c.data("validation"+a.validatorName+"Message",a.message),setTimeout(function(){c.trigger("change.validation")},1))}));return!1}},ajax:{name:"ajax",init:function(c,b){return{validatorName:b,url:c.data("validation"+b+"Ajax"),lastValue:c.val(),lastValid:!0,lastFinished:!0}},validate:function(c,b,a){return""+a.lastValue==""+b&&!0===a.lastFinished?!1===a.lastValid:(!0===a.lastFinished&&(a.lastValue=
b,a.lastValid=!0,a.lastFinished=!1,d.ajax({url:a.url,data:"value="+b+"&field="+c.attr("name"),dataType:"json",success:function(f){""+a.lastValue==""+f.value&&(a.lastValid=!!f.valid,f.message&&(a.message=f.message),a.lastFinished=!0,c.data("validation"+a.validatorName+"Message",a.message),setTimeout(function(){c.trigger("change.validation")},1))},failure:function(){a.lastValid=!0;a.message="ajax call failed";a.lastFinished=!0;c.data("validation"+a.validatorName+"Message",a.message);setTimeout(function(){c.trigger("change.validation")},
1)}})),!1)}},regex:{name:"regex",init:function(c,b){var a;return{regex:(a=c.data("validation"+b+"Regex"),RegExp("^"+a+"$"))}},validate:function(c,b,a){return!a.regex.test(b)&&!a.negative||a.regex.test(b)&&a.negative}},required:{name:"required",init:function(c,b){return{}},validate:function(c,b,a){return!(0!==b.length||a.negative)||!!(0<b.length&&a.negative)},blockSubmit:!0},match:{name:"match",init:function(c,b){var a=c.parents("form").first().find('[name="'+c.data("validation"+b+"Match")+'"]').first();
return a.bind("validation.validation",function(){c.trigger("change.validation",{submitting:!0})}),{element:a}},validate:function(c,b,a){return b!==a.element.val()&&!a.negative||b===a.element.val()&&a.negative},blockSubmit:!0},max:{name:"max",init:function(c,b){return{max:c.data("validation"+b+"Max")}},validate:function(c,b,a){return parseFloat(b,10)>parseFloat(a.max,10)&&!a.negative||parseFloat(b,10)<=parseFloat(a.max,10)&&a.negative}},min:{name:"min",init:function(c,b){return{min:c.data("validation"+
b+"Min")}},validate:function(c,b,a){return parseFloat(b)<parseFloat(a.min)&&!a.negative||parseFloat(b)>=parseFloat(a.min)&&a.negative}},maxlength:{name:"maxlength",init:function(c,b){return{maxlength:c.data("validation"+b+"Maxlength")}},validate:function(c,b,a){return b.length>a.maxlength&&!a.negative||b.length<=a.maxlength&&a.negative}},minlength:{name:"minlength",init:function(c,b){return{minlength:c.data("validation"+b+"Minlength")}},validate:function(c,b,a){return b.length<a.minlength&&!a.negative||
b.length>=a.minlength&&a.negative}},maxchecked:{name:"maxchecked",init:function(c,b){var a=c.parents("form").first().find('[name="'+c.attr("name")+'"]');return a.bind("click.validation",function(){c.trigger("change.validation",{includeEmpty:!0})}),{maxchecked:c.data("validation"+b+"Maxchecked"),elements:a}},validate:function(c,b,a){return a.elements.filter(":checked").length>a.maxchecked&&!a.negative||a.elements.filter(":checked").length<=a.maxchecked&&a.negative},blockSubmit:!0},minchecked:{name:"minchecked",
init:function(c,b){var a=c.parents("form").first().find('[name="'+c.attr("name")+'"]');return a.bind("click.validation",function(){c.trigger("change.validation",{includeEmpty:!0})}),{minchecked:c.data("validation"+b+"Minchecked"),elements:a}},validate:function(c,b,a){return a.elements.filter(":checked").length<a.minchecked&&!a.negative||a.elements.filter(":checked").length>=a.minchecked&&a.negative},blockSubmit:!0}},builtInValidators:{email:{name:"Email",type:"shortcut",shortcut:"validemail"},validemail:{name:"Validemail",
type:"regex",regex:"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,10}",message:"Not a valid email address\x3c!-- data-validator-validemail-message to override --\x3e"},passwordagain:{name:"Passwordagain",type:"match",match:"password",message:"Does not match the given password\x3c!-- data-validator-paswordagain-message to override --\x3e"},positive:{name:"Positive",type:"shortcut",shortcut:"number,positivenumber"},negative:{name:"Negative",type:"shortcut",shortcut:"number,negativenumber"},number:{name:"Number",
type:"regex",regex:"([+-]?\\d+(\\.\\d*)?([eE][+-]?[0-9]+)?)?",message:"Must be a number\x3c!-- data-validator-number-message to override --\x3e"},integer:{name:"Integer",type:"regex",regex:"[+-]?\\d+",message:"No decimal places allowed\x3c!-- data-validator-integer-message to override --\x3e"},positivenumber:{name:"Positivenumber",type:"min",min:0,message:"Must be a positive number\x3c!-- data-validator-positivenumber-message to override --\x3e"},negativenumber:{name:"Negativenumber",type:"max",max:0,
message:"Must be a negative number\x3c!-- data-validator-negativenumber-message to override --\x3e"},required:{name:"Required",type:"required",message:"This is required\x3c!-- data-validator-required-message to override --\x3e"},checkone:{name:"Checkone",type:"minchecked",minchecked:1,message:"Check at least one option\x3c!-- data-validation-checkone-message to override --\x3e"}}},z=function(c){return c.toLowerCase().replace(/(^|\s)([a-z])/g,function(b,a,f){return a+f.toUpperCase()})},C=function(c){var b=
c.val(),a=c.attr("type");return"checkbox"===a&&(b=c.is(":checked")?b:""),"radio"===a&&(b=0<d('input[name="'+c.attr("name")+'"]:checked').length?b:""),b};d.fn.jqBootstrapValidation=function(c){return y.methods[c]?y.methods[c].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof c&&c?(d.error("Method "+c+" does not exist on jQuery.jqBootstrapValidation"),null):y.methods.init.apply(this,arguments)};d.jqBootstrapValidation=function(c){d(":input").not("[type=image],[type=submit]").jqBootstrapValidation.apply(this,
arguments)}}(jQuery);